# MAIN base
#baseURL = "https://apsho-hugo.netlify.app/"
# baseURL = "https://euphonious-dragon-a64645.netlify.app/"
baseURL = "https://presilia.id/"
languageCode = "en-us"
title = "Presilia | Workforce Management"
theme = "apsho"

DefaultContentLanguage = "en"
defaultContentLanguageInSubdir= false

[languages]
  [languages.en]
    title = "Presilia | Workforce Management"
    languageName = "English"
    weight = 1
  [languages.id]
    title = "Presilia | Workforce Management"
    languageName = "Indonesia"
    weight = 2

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#feature"
    weight = 2
[[menu.main]]
    name = "Services"
    url = "#faq"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
##[[menu.sitemap]]
##    name = "Latest Article"
##    url = "/blog"
##    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    #url = "/Privacy"
    weight = 3
[[menu.sitemap]]
    name = "Terms & Conditions"
    #url = "/terms-and-conditions"
    weight = 4
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 5

# Footer Address
[params.address]
address = "Jl. RS. Fatmawati no. 75"
email = "info@presilia.id"
phone = "+(62) 833 5272 332"

# Footer Social
[params.social]
facebook = "https://www.facebook.com/pg/#"
twitter = "https://twitter.com/#"
github = "https://github.com/#"

[params]

# Header
logo = "images/logo.png"
formspreeURL = "https://formspree.io/f/xyyovlpz"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Get the latest updates"
copyright1 = "All right reserved"
copyright2 = "Copyright Â© PT. Infomedia Solusi Humanika {year}"

#contact
email = "info@presilia.id"
